export const ONE_BUTTON = '1';
export const TWO_BUTTON = '2';
export const THREE_BUTTON = '3';
export const FOUR_BUTTON = '4';
export const FIVE_BUTTON = '5';
export const SIX_BUTTON = '6';
export const SEVEN_BUTTON = '7';
export const EIGHT_BUTTON = '8';
export const NINE_BUTTON = '9';
export const ZERO_BUTTON = '0';
export const CLEAR_BUTTON = 'C';
export const DELETE_BUTTON = '←'
export const DIVISION_BUTTON = '÷';
export const MULTIPLICATION_BUTTON = '×';
export const SUBTRACTION_BUTTON = '−';
export const ADDITION_BUTTON = '+';
export const COMPUTE_BUTTON = '=';
export const NO_OP = 'NO_OP';